/// Flutter icons AayanIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AayanIcons
///      fonts:
///       - asset: fonts/AayanIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AayanIcons {
  AayanIcons._();

  static const _kFontFam = 'AayanIcons';
  static const String _kFontPkg = null;

  static const IconData icon_material_file_upload = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_material_info = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_material_insert_drive_file = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_material_payment = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_metro_wrench = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_open_account_logout = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_awesome_calendar_check = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_awesome_car = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_us = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_feather_alert_triangle = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lease = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translate = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_document_840148 = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData servicing = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchase = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
